### ISSUE TITLE
decode_image.c not included in cmake

### ISSUE THREAD

**Issue by app-z** [nopnop2002/esp-idf-st7789#13]
/root/.espressif/tools/xtensa-esp32-elf/esp-2020r1-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/main/libmain.a(main.c.obj):(.literal.JPEGTest+0x8): undefined reference to `decode_image'

You probably forget it:
set(COMPONENT_SRCS main.c st7789.c fontx.c decode_image.c)

**Comment by nopnop2002** [comment]
Thank you for report.

Fixed it.
