### ISSUE TITLE
This Project can not work on esp32C3

### ISSUE THREAD

**Issue by Supowang1989** [nopnop2002/esp-idf-st7789#27]
MOSI ： GPIO10
SCLK ：GPIO7 
CS：-1
DC：GPIO1
RESET：GPIO3
BL： GPIO0 

Can anyone help me check it，Thanks！

**Comment by nopnop2002** [comment]
Why CS:-1？


You need to use CS gpio.

If you don't use CS gpio, you should always set CS of TFT to LOW.

**Comment by Supowang1989** [comment]
Thanks for your reply，CS has connect to GND  on my  board

**Comment by Supowang1989** [comment]
> Why CS:-1？
> 
> You need to use CS gpio.
> 
> If you don't use CS gpio, you should always set CS of TFT to LOW.

Thanks for your reply，CS GPIO has connect to GND on my board

**Comment by nopnop2002** [comment]
For some reason, there are development boards that cannot use GPIO06, GPIO08, GPIO09, GPIO19 for SPI clock pins.
According to the ESP32C3 specifications, these pins can also be used as SPI clocks.
I used a raw ESP-C3-13 to verify that these pins could be used as SPI clocks.

Try to change SPI Clock pin.

**Comment by Supowang1989** [comment]
> > Why CS:-1？
> > You need to use CS gpio.
> > If you don't use CS gpio, you should always set CS of TFT to LOW.
> 
> Thanks for your reply，CS GPIO has connect to GND on my board
[Schematic_ESP32-C3-13-EVB-V1_2022-02-16.pdf](https://github.com/nopnop2002/esp-idf-st7789/files/8076461/Schematic_ESP32-C3-13-EVB-V1_2022-02-16.pdf)

this is my sch file

**Comment by nopnop2002** [comment]
>this is my sch file


I don't know reason even if I look at it.

I tested with this.

![ESP-C3-13-5](https://user-images.githubusercontent.com/6020549/154190718-8cc30e2c-7ea3-41f5-a4aa-75af856dcdcd.JPG)

**Comment by Supowang1989** [comment]
> > this is my sch file
> 
> I don't know reason even if I look at it.

OK ，still very grateful
