### ISSUE TITLE
did you original this st7789 library?

### ISSUE THREAD

**Issue by wjcarpenter** [nopnop2002/esp-idf-st7789#29]
I'm curious if you created this st7789 library or if it's derived from something else. I'm asking because I'm planning to use it in a small project of my own, and I want to give proper credit in my documentation. (In any case, thanks for your work here.)

**Comment by nopnop2002** [comment]
I developed it based on this.

These are all my originals.

https://github.com/nopnop2002/esp-idf-ili9340


The two repositories are very similar.

ST7789 only worked in SPI mode = 2, so I split the repository.

**Comment by wjcarpenter** [comment]
Thanks for confiming.
