### ISSUE TITLE
demo worked, but only 240x240?

### ISSUE THREAD

**Issue by chopin1998** [nopnop2002/esp-idf-st7789#36]
my lcd is 320x240, i have config in menuconfig, set width to 320, height to 240

but the demo only show 240x240?

**Comment by nopnop2002** [comment]
did you save the config?
Enter the s key in menuconfig.

![config](https://github.com/nopnop2002/esp-idf-st7789/assets/6020549/618744c2-9815-43c2-83c8-e29e0af9a0de)

![241339803-7b2f39df-6fc6-44d3-b0e7-8776573035b3](https://github.com/nopnop2002/esp-idf-st7789/assets/6020549/48f25015-09da-4957-a34e-0ce46d690653)
