### ISSUE TITLE
SPI data is sampled on rising edge of clock, wrong mode?

### ISSUE THREAD

**Issue by DaveDavenport** [nopnop2002/esp-idf-st7789#38]
Connecting a waveshare screen to an esp32-s3 it did not work, after looking in datasheet of the screen:
(https://www.waveshare.com/w/upload/a/ae/ST7789_Datasheet.pdf)

![image](https://github.com/nopnop2002/esp-idf-st7789/assets/406245/b6e5c89b-971e-4862-9256-8ef6d2072702)

and the timings:
![image](https://github.com/nopnop2002/esp-idf-st7789/assets/406245/190bc62d-e647-4928-8eb1-2c840c631c06)

it looks like that the data is sampled on the rising edge of the clock. This should indicate it is spi mode 0 or 3. In diagram clock idles low so 0?.  Changing this also fixes the black screen and I get a working demo. 
![image](https://github.com/nopnop2002/esp-idf-st7789/assets/406245/4b4b838d-1450-4bd9-a01f-3d7c56c8f056)

I am not sure if waveshare uses a slightly different version of the chip? 

Thanks for the library.

(I got a déjà vu feeling, but could not find earlier issue. might have been somewhere else.).

**Comment by nopnop2002** [comment]
Changed SPI mode from 2 to 3.
