### ISSUE TITLE
Variable 'size' overflows in function lcdDrawFinish() when setting the resolution to 320*240

### ISSUE THREAD

**Issue by MNDJ777** [nopnop2002/esp-idf-st7789#40]
My 320*240 TFT  can only displays a limited part when enabling frame buffer, then I found that variable 'size' overflowed, where it should be set to uint32_t.  It doesn't work under resolution at 320*240,
 https://github.com/nopnop2002/esp-idf-st7789/blob/8adf642cc26cf5d5815fb09d3006d063cb7c826e/components/st7789/st7789.c#L1069

**Comment by nopnop2002** [comment]
Will it work correctly if you change to uint32_t in 320x240 TFT?

**Comment by MNDJ777** [comment]
> Will it work correctly if you change to uint32_t in 320x240 TFT?

Yes, it works perfectly now.
before:
![51eb34eb51690ef54e29fec797d312e](https://github.com/nopnop2002/esp-idf-st7789/assets/63846910/53053df9-adec-41fe-9992-8d6232c5ed76)
after:
![6c12f8d9c7e022f1055da09d2ff5f68](https://github.com/nopnop2002/esp-idf-st7789/assets/63846910/f994949e-60e9-4e4b-b23e-91461439bc26)

**Comment by nopnop2002** [comment]
Thank you for the report.
Fixed.
