### ISSUE TITLE
About create font

### ISSUE THREAD

**Issue by nguyentrungg** [nopnop2002/esp-idf-st7789#43]
Hi. Thank you for creating a perfect library.
I want to ask you how to create file .FNT from .ttf file example: concielian.ttf.
Thank you so much.

**Comment by nopnop2002** [comment]
TTF fonts are scalable fonts.

FNT fonts are bitmap fonts.

Searching for this keyword brings up several hits, but I have never tried it.

```
convert scalable fonts to bitmap font
```

**Comment by nopnop2002** [comment]
# Convert from TTF font to FONTX font  
step1)   
Download WFONTX64.exe from [here](https://github.com/nemuisan/WFONTX64/releases).
Developer page is [here](https://github.com/nemuisan/WFONTX64).   

step2)   
Select ttf font.   
![WFINTX64-1](https://github.com/user-attachments/assets/0fc874b5-4ffa-4cba-b22f-9430b406ba04)

step3)   
Enter Height, Width, FontX2 name.   
Specify half of Height for Width.   
Specify your favorite font name in the FontX2 name field using up to 8 characters.   
![WFINTX64-2](https://github.com/user-attachments/assets/6cdc69af-891e-4f43-8c65-8db0a12e10d7)

step4)   
Specify the file name to save.   
![WFINTX64-3](https://github.com/user-attachments/assets/3588bca1-e03f-42ca-bbe0-d8f9627b20c9)

step5)   
Specify the font style as required.   
![WFINTX64-4](https://github.com/user-attachments/assets/9246bd4f-615c-4676-a451-a8c2a39b83e5)

step6)   
Press the RUN button to convert TTF fonts to FONTX format.   
![WFINTX64-4](https://github.com/user-attachments/assets/68530333-6375-4796-b0ca-38b3bd1ffc98)

![TTF_FONT](https://github.com/user-attachments/assets/507c7cc5-f82f-45a6-8f13-11d0fda50bc7)

**Comment by nguyentrungg** [comment]
Hi, I saw you post an answer with instructions on how to convert ttf file to fnt file using some tool on ubuntu. I remember it was sudo otf2bdf, but I don't remember clearly. Please remind me, I would appreciate it.

**Comment by nopnop2002** [comment]
This is OpenType to BDF font converter.
https://formulae.brew.sh/formula/otf2bdf

There is probably no command on Linux to convert from TTF fonts to FONTX fonts.

Use this after converting from TTF to BDF.
http://www.wheel.gr.jp/~dai/software/bdf2fontx.c

```
cc -o bdf2fontx bdf2fontx.c
./bdf2fontx < spleen-16x32.bdf > spleen32.fnt
```
