### ISSUE TITLE
Custom Font creation

### ISSUE THREAD

**Issue by arunyava** [nopnop2002/esp-idf-st7789#44]
Hi,
please help to create custom font .I look fontfx.exe .but it's not found .Can you please explain the steps. I am new in this field

**Comment by nopnop2002** [comment]
[FONTX Editor](http://elm-chan.org/fsw/fontxedit.zip)

Please follow the README.

**Comment by arunyava** [comment]
while clicking the link it shows "not found".

**Comment by arunyava** [comment]
its downloaded sir. thanks a lot for your valuable support

**Comment by arunyava** [comment]
how can we select ttf file for custom font creation. Is same font map file can be used for different size letter ,means normal ,bold etc. How can implement that? please help.

**Comment by nopnop2002** [comment]
>how can we select ttf file for custom font creation.


All the information you need is written in the readme.

Please read the readme carefully.

**Comment by arunyava** [comment]
hi sir,
How can make the letter bold

**Comment by nopnop2002** [comment]
Please check bold.

![WFINTX64-4](https://github.com/user-attachments/assets/3938d3ac-9452-4187-aa99-a8e3a73551db)

**Comment by arunyava** [comment]
![img](https://github.com/user-attachments/assets/c3f36a53-37ee-4104-bf41-a637253649a0)
this is the exe i got from that link. It has no option. what do you do sir .

**Comment by arunyava** [comment]
Hi Sir,
I am facing one more issue. if i set color as yellow but the font letters are in blue.  
                         GetFontx(0, buffer, &fontWidth, &fontHeight);
			  lcdFillScreen(&dev, BLACK);
			  lcdSetFontDirection(&dev, 3);
				color = YELLOW;
				strcpy((char *)ascii, "123456789101234567");
				lcdDrawString(&dev, (fontHeight*1)-1,CONFIG_HEIGHT-12, ascii, color);
what was the issue ? Can you please help me?

**Comment by nopnop2002** [comment]
Is BLUE displayed correctly?

```
strcpy((char )ascii, "123456789101234567");
lcdDrawString(&dev, (fontHeight1)-1,CONFIG_HEIGHT-12, ascii, BLUE);
```

**Comment by arunyava** [comment]
no , it changed as yellow

**Comment by nopnop2002** [comment]
There are no problems with this project.


It's a problem with your code.



You need to share the entire project, not just a piece of code.

![IMG_5563](https://github.com/user-attachments/assets/b6c37ed0-d70f-4430-a310-5397ca6a47d0)

**Comment by arunyava** [comment]
Sorry sir , its not your project issue. Its my project issue . I need help to rectify the issue. Thanks in advance. I'm working  in LPC1768 board.

**Comment by nopnop2002** [comment]
I don't have LPC1768 board.

**Comment by nopnop2002** [comment]
The issues of creating a custom font has been resolved, so I close it.
