### ISSUE TITLE
Request for Multipixelusage

### ISSUE THREAD

**Issue by arunyava** [nopnop2002/esp-idf-st7789#45]
Hi 
Can you please explain the usage of multipixel

**Comment by nopnop2002** [comment]
https://github.com/nopnop2002/esp-idf-st7789/blob/master/main/main.c#L625

**Comment by arunyava** [comment]
hi sir , how can we use this multi pixel in lcd draw string function ? Please help. Thanks in advance

**Comment by nopnop2002** [comment]
I can't answer because I don't understand the situation you're requesting.

I need an explanation of why you want to use the multipixel function.

Multipixel functions draw the same color consecutively.

This feature is useless when drawing strings.
