### ISSUE TITLE
VS Code / VStudio implementation

### ISSUE THREAD

**Issue by Krki012** [nopnop2002/esp-idf-st7789#48]
Hi, I'm a bit new to esp-idf and all this esp cloning so I'm here to seek help on how to implement this library in my project. Which files do I copy where, which do I leave out, what do I do in SDK (idk what that even is) etc. All of this relates to VSCode (VStudio is basically the same). I'd like to avoid esp-idf as a program as much as I can. Sorry to open the issue for something like this.

**Comment by nopnop2002** [comment]
I don't use VS code/Vstudio.
Because they are too lacking in functionality.
Probably these cannot meet your needs.
Use bash.
```
cd esp-idf-st7789
cp -r components your_project
cd your_project
rm sdkconfig
idf.py menuconfig
idf.py build
````

**Comment by nopnop2002** [comment]
Since there is no reply, I will close it.
