### ISSUE TITLE
Fonts larger than 32

### ISSUE THREAD

**Issue by MFranches** [nopnop2002/esp-idf-st7789#49]
Hi, is there a way to have fonts larger than 32?
When i tried, by using my own fonts tailored to sizes 48 and 64, I receive the error
"Fontx:%s is too big font size"
I see the limitation is determined by FontxGlyphBufSize > (32*32/8)
Why?
Regards

**Comment by nopnop2002** [comment]
The latest version supports large font sizes.

![394041476-5abb8cee-03b6-43de-b77f-e6c4813543c6](https://github.com/user-attachments/assets/9bd83621-52db-4e26-bfd7-871f4e3919fc)

**Comment by MFranches** [comment]
Thanks for the quick reply
I owe you a beer!!
