### ISSUE TITLE
fontx.c needs to be added to CMakeLists in order to compile

### ISSUE THREAD

**Issue by rglissmann** [nopnop2002/esp-idf-st7789#9]
Hi. Thanks for your effort creating this library. I had to add fontx.c to compile without errors. The create partition line will load the STIFFs.

set(COMPONENT_SRCS "st7789.c" "main.c" fontx.c)
set(COMPONENT_ADD_INCLUDEDIRS ".")

register_component()
spiffs_create_partition_image(storage ../font FLASH_IN_PROJECT)

**Comment by nopnop2002** [comment]
Thank you for your report.

I will reflect that.
